import './styles.css';
import { auth, db } from './firebase.js';
import { signInWithEmailAndPassword, signOut, onAuthStateChanged } from 'firebase/auth';
import { collection, doc, getDoc, onSnapshot, orderBy, query, runTransaction, serverTimestamp, updateDoc } from 'firebase/firestore';

const root=document.querySelector('#app');
let user=null, admin=null, operations=[], otpRequests=[], unsub=[];
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const money=(v=0)=>`APX ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const when=(t)=>t?.toDate?.()?.toLocaleString?.()||'—';
const stop=()=>{unsub.forEach(f=>f?.());unsub=[]};

function login(){root.innerHTML=`<main class="login"><section><div class="brand">Apex<span>Pay</span> <b>ADMIN</b></div><h1>Network operations console</h1><p>Authorized staff only. Review queued transactions, OTP challenges and money-flow exceptions.</p><form id="loginForm"><label>Email<input id="email" type="email" required/></label><label>Password<input id="password" type="password" required/></label><button>Sign in</button><p id="msg"></p></form></section></main>`;document.querySelector('#loginForm').onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#msg');const emailInput=document.querySelector('#email');const passwordInput=document.querySelector('#password');try{await signInWithEmailAndPassword(auth,emailInput.value.trim(),passwordInput.value)}catch(err){msg.textContent=err.message}}}

function denied(){root.innerHTML=`<main class="login"><section><div class="brand">Apex<span>Pay</span> <b>ADMIN</b></div><h1>Access not authorized</h1><p>This account is authenticated but is not registered as an active ApexPay administrator.</p><button id="out">Sign out</button></section></main>`;document.querySelector('#out').onclick=()=>signOut(auth)}

function layout(){const queued=operations.filter(x=>x.status==='queued'||x.status==='otp_pending'||x.status==='approved').length;const otp=otpRequests.filter(x=>!['verified','rejected'].includes(x.status)).length;root.innerHTML=`<div class="shell"><aside><div class="brand">Apex<span>Pay</span><b>OPS</b></div><div class="admin"><strong>${esc(admin?.name||user.email)}</strong><small>${esc(admin?.role||'operations')}</small></div><nav><a class="active" href="#ops">Operations</a><a href="#otp">OTP desk</a><a href="#audit">Audit</a></nav><button id="logout">Sign out</button></aside><main><header><div><p class="kicker">NETWORK CONTROL</p><h1>Operations desk</h1></div><div class="live"><i></i> Live</div></header><section class="stats"><article><small>Queued operations</small><strong>${queued}</strong></article><article><small>OTP actions</small><strong>${otp}</strong></article><article><small>Completed</small><strong>${operations.filter(x=>x.status==='success').length}</strong></article><article><small>Failed / rejected</small><strong>${operations.filter(x=>['failed','rejected'].includes(x.status)).length}</strong></article></section><section class="panel"><div class="panel-head"><div><h2>Money operation queue</h2><p>Processing commits wallet balances and ledger entries atomically. OTP-protected operations require a verified challenge first.</p></div></div><div id="opsTable"></div></section><section class="panel"><div class="panel-head"><div><h2>OTP processing queue</h2><p>Verify or reject submitted OTP challenges before protected transfers can settle.</p></div></div><div id="otpTable"></div></section></main></div>`;document.querySelector('#logout').onclick=()=>signOut(auth);renderTables()}

function renderTables(){const ops=document.querySelector('#opsTable');if(ops)ops.innerHTML=operations.length?`<div class="table"><div class="row head"><span>Reference</span><span>Type</span><span>Amount</span><span>Status</span><span>Action</span></div>${operations.map(o=>`<div class="row"><span><b>${esc(o.reference||o.id)}</b><small>${when(o.createdAt)}</small></span><span>${esc(o.type||'transfer')}</span><span>${money(o.amount)}</span><span><em class="${esc(o.status||'queued')}">${esc(o.status||'queued')}</em></span><span>${['queued','approved','otp_pending'].includes(o.status||'queued')?`<button class="approve" data-id="${esc(o.id)}">Process</button><button class="reject" data-id="${esc(o.id)}">Reject</button>`:'—'}</span></div>`).join('')}</div>`:'<div class="empty">No operations in queue.</div>';
const ot=document.querySelector('#otpTable');if(ot)ot.innerHTML=otpRequests.length?`<div class="table"><div class="row otphead"><span>Request</span><span>User</span><span>Submitted</span><span>Status</span><span>Action</span></div>${otpRequests.map(o=>`<div class="row otphead"><span><b>${esc(o.reference||o.id)}</b><small>${when(o.createdAt)}</small></span><span>${esc(o.userEmail||o.userId||'—')}</span><span>${esc(o.submittedCode||'—')}</span><span><em class="${esc(o.status||'pending')}">${esc(o.status||'pending')}</em></span><span>${['pending','submitted'].includes(o.status||'pending')?`<button class="verifyOtp" data-id="${esc(o.id)}">Verify</button><button class="rejectOtp" data-id="${esc(o.id)}">Reject</button>`:'—'}</span></div>`).join('')}</div>`:'<div class="empty">No OTP requests.</div>';

document.querySelectorAll('.approve').forEach(b=>b.onclick=()=>processOperation(b.dataset.id));document.querySelectorAll('.reject').forEach(b=>b.onclick=()=>rejectOperation(b.dataset.id));document.querySelectorAll('.verifyOtp').forEach(b=>b.onclick=()=>setOtp(b.dataset.id,'verified'));document.querySelectorAll('.rejectOtp').forEach(b=>b.onclick=()=>setOtp(b.dataset.id,'rejected'))}

async function processOperation(id){const opRef=doc(db,'moneyOperations',id);try{await runTransaction(db,async tx=>{const snap=await tx.get(opRef);if(!snap.exists())throw new Error('Operation not found');const op=snap.data();if(!['queued','approved','otp_pending'].includes(op.status))throw new Error('Already processed');if(op.otpRequestId){const otpRef=doc(db,'otpRequests',op.otpRequestId);const otpSnap=await tx.get(otpRef);if(!otpSnap.exists()||otpSnap.data().status!=='verified')throw new Error('OTP has not been verified');}if(!op.fromWalletId||!op.toWalletId)throw new Error('Wallet IDs missing');const fromRef=doc(db,'wallets',op.fromWalletId),toRef=doc(db,'wallets',op.toWalletId);const fromSnap=await tx.get(fromRef);const toSnap=await tx.get(toRef);if(!fromSnap.exists()||!toSnap.exists())throw new Error('Wallet not found');const amount=Number(op.amount||0),fromBal=Number(fromSnap.data().balance||0),toBal=Number(toSnap.data().balance||0);if(amount<=0)throw new Error('Invalid amount');if(fromBal<amount)throw new Error('Insufficient balance');tx.update(fromRef,{balance:fromBal-amount,updatedAt:serverTimestamp()});tx.update(toRef,{balance:toBal+amount,updatedAt:serverTimestamp()});tx.set(doc(db,'ledger',`${id}_debit`),{operationId:id,walletId:op.fromWalletId,direction:'debit',amount,createdAt:serverTimestamp(),adminId:user.uid});tx.set(doc(db,'ledger',`${id}_credit`),{operationId:id,walletId:op.toWalletId,direction:'credit',amount,createdAt:serverTimestamp(),adminId:user.uid});tx.update(opRef,{status:'success',processedAt:serverTimestamp(),processedBy:user.uid})});alert('Operation processed successfully.')}catch(err){alert(err.message)}}
async function rejectOperation(id){try{await updateDoc(doc(db,'moneyOperations',id),{status:'rejected',processedAt:serverTimestamp(),processedBy:user.uid})}catch(err){alert(err.message)}}
async function setOtp(id,status){try{await updateDoc(doc(db,'otpRequests',id),{status,processedAt:serverTimestamp(),processedBy:user.uid})}catch(err){alert(err.message)}}

function subscribe(){stop();unsub.push(onSnapshot(query(collection(db,'moneyOperations'),orderBy('createdAt','desc')),s=>{operations=s.docs.map(d=>({id:d.id,...d.data()}));layout()}));unsub.push(onSnapshot(query(collection(db,'otpRequests'),orderBy('createdAt','desc')),s=>{otpRequests=s.docs.map(d=>({id:d.id,...d.data()}));layout()}))}

onAuthStateChanged(auth,async u=>{stop();user=u;if(!u){admin=null;login();return}try{const snap=await getDoc(doc(db,'admins',u.uid));if(!snap.exists()||snap.data().active!==true){admin=null;denied();return}admin=snap.data();layout();subscribe()}catch{denied()}});
