import './styles.css';
import { auth, db } from './firebase.js';
import { createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged, updateProfile } from 'firebase/auth';
import { collection, doc, getDoc, onSnapshot, orderBy, query, serverTimestamp, setDoc, updateDoc, where } from 'firebase/firestore';

const root=document.querySelector('#app');
let user=null,wallet=null,operations=[],unsub=[];
const esc=(v='')=>String(v).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;');
const money=(v=0)=>`APX ${Number(v||0).toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})}`;
const stop=()=>{unsub.forEach(f=>f?.());unsub=[]};

function authView(mode='signin'){const signup=mode==='signup';root.innerHTML=`<main class="auth"><section><div class="brand">Apex<span>Pay</span> <b>WALLET</b></div><h1>${signup?'Create your wallet':'Welcome back'}</h1><p>${signup?'Join the APX network and receive a wallet identity.':'Sign in to your ApexPay wallet.'}</p><form id="authForm">${signup?'<label>Full name<input id="name" required/></label>':''}<label>Email<input id="email" type="email" required/></label><label>Password<input id="password" type="password" minlength="6" required/></label><button>${signup?'Create wallet':'Sign in'}</button><p id="msg"></p></form><a href="#/${signup?'signin':'signup'}">${signup?'Already have a wallet? Sign in':'New customer? Create wallet'}</a></section></main>`;document.querySelector('#authForm').onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#msg');const email=document.querySelector('#email').value.trim(),password=document.querySelector('#password').value;try{if(signup){const name=document.querySelector('#name').value.trim();const cred=await createUserWithEmailAndPassword(auth,email,password);await updateProfile(cred.user,{displayName:name});await setDoc(doc(db,'wallets',cred.user.uid),{ownerId:cred.user.uid,email:cred.user.email,displayName:name,balance:0,status:'active',createdAt:serverTimestamp(),updatedAt:serverTimestamp()})}else await signInWithEmailAndPassword(auth,email,password)}catch(err){msg.textContent=err.message}}}

function appView(){const pending=operations.filter(o=>!['success','rejected','failed'].includes(o.status)).length;root.innerHTML=`<div class="shell"><header><div class="brand">Apex<span>Pay</span><b>WALLET</b></div><button id="logout">Sign out</button></header><main><section class="welcome"><div><p class="kicker">CUSTOMER WALLET</p><h1>${esc(wallet?.displayName||user.displayName||'Your wallet')}</h1><p>${esc(user.email)}</p></div><div class="wallet-id">Wallet ID <b>${esc(user.uid)}</b></div></section><section class="balance"><small>Available balance</small><strong>${money(wallet?.balance)}</strong><span>${pending} operation${pending===1?'':'s'} pending</span></section><section class="grid"><article class="panel"><h2>Send APX</h2><p>Create a transfer request. Balance changes only after OTP verification and admin processing.</p><form id="sendForm"><label>Recipient wallet ID<input id="recipient" required placeholder="Recipient UID"/></label><label>Amount<input id="amount" type="number" min="0.01" step="0.01" required placeholder="0.00"/></label><label>Note<input id="note" maxlength="120" placeholder="Optional note"/></label><button>Request transfer</button><p id="sendMsg"></p></form></article><article class="panel"><h2>Submit OTP</h2><p>Enter the OTP provided by ApexPay operations for your pending request.</p><form id="otpForm"><label>OTP request ID<input id="otpId" required placeholder="OTP request ID"/></label><label>OTP code<input id="otpCode" required inputmode="numeric" maxlength="6" placeholder="000000"/></label><button>Submit OTP</button><p id="otpMsg"></p></form></article></section><section class="panel history"><h2>Operation history</h2><div id="history"></div></section></main></div>`;document.querySelector('#logout').onclick=()=>signOut(auth);bindForms();renderHistory()}

function renderHistory(){const h=document.querySelector('#history');if(!h)return;h.innerHTML=operations.length?operations.map(o=>`<div class="op"><div><strong>${esc(o.reference||o.id)}</strong><small>${esc(o.type||'transfer')} → ${esc(o.toWalletId||'—')}</small></div><b>${money(o.amount)}</b><em class="${esc(o.status||'queued')}">${esc(o.status||'queued')}</em>${o.otpRequestId?`<code>${esc(o.otpRequestId)}</code>`:''}</div>`).join(''):'<div class="empty">No operations yet.</div>'}

function bindForms(){const send=document.querySelector('#sendForm');send.onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#sendMsg');const toWalletId=document.querySelector('#recipient').value.trim();const amount=Number(document.querySelector('#amount').value);const note=document.querySelector('#note').value.trim();if(toWalletId===user.uid){msg.textContent='You cannot send to your own wallet.';return}if(amount<=0){msg.textContent='Enter a valid amount.';return}try{const target=await getDoc(doc(db,'wallets',toWalletId));if(!target.exists()){msg.textContent='Recipient wallet not found.';return}const opRef=doc(collection(db,'moneyOperations'));const otpRef=doc(collection(db,'otpRequests'));const reference=`APX-${Date.now()}-${opRef.id.slice(0,5).toUpperCase()}`;await setDoc(otpRef,{operationId:opRef.id,reference,userId:user.uid,userEmail:user.email,status:'pending',createdAt:serverTimestamp()});await setDoc(opRef,{reference,type:'transfer',fromWalletId:user.uid,toWalletId,amount,note,status:'otp_pending',otpRequestId:otpRef.id,createdBy:user.uid,createdAt:serverTimestamp()});send.reset();msg.innerHTML=`Request created. OTP request ID: <b>${esc(otpRef.id)}</b>`}catch(err){msg.textContent=err.message}};
const otp=document.querySelector('#otpForm');otp.onsubmit=async e=>{e.preventDefault();const msg=document.querySelector('#otpMsg');const id=document.querySelector('#otpId').value.trim(),code=document.querySelector('#otpCode').value.trim();if(!/^\d{6}$/.test(code)){msg.textContent='Enter the 6-digit OTP.';return}try{await updateDoc(doc(db,'otpRequests',id),{submittedCode:code,status:'submitted',submittedAt:serverTimestamp()});otp.reset();msg.textContent='OTP submitted for admin verification.'}catch(err){msg.textContent=err.message}}}

function subscribe(){stop();unsub.push(onSnapshot(doc(db,'wallets',user.uid),s=>{wallet=s.exists()?s.data():null;appView()}));const q=query(collection(db,'moneyOperations'),where('createdBy','==',user.uid),orderBy('createdAt','desc'));unsub.push(onSnapshot(q,s=>{operations=s.docs.map(d=>({id:d.id,...d.data()}));appView()}))}

onAuthStateChanged(auth,async u=>{stop();user=u;if(!u){wallet=null;operations=[];authView(location.hash==='#/signup'?'signup':'signin');return}const snap=await getDoc(doc(db,'wallets',u.uid));if(!snap.exists())await setDoc(doc(db,'wallets',u.uid),{ownerId:u.uid,email:u.email,displayName:u.displayName||'',balance:0,status:'active',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});wallet=(await getDoc(doc(db,'wallets',u.uid))).data();appView();subscribe()});
window.addEventListener('hashchange',()=>{if(!auth.currentUser)authView(location.hash==='#/signup'?'signup':'signin')});
